apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: proxy-sdk-deployment
  name: proxy-sdk-deployment
spec:
  replicas: {{ .Values.sdkProxyReplicaCount }}
  selector:
    matchLabels:
      app: proxy-sdk-deployment
  template:
    metadata:
      labels:
        app: proxy-sdk-deployment
    spec:
      containers:
        - name: split-proxy
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          startupProbe:
            httpGet:
              path: /health/application
              port: 3010
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
          livenessProbe:
            httpGet:
              path: /health/application
              port: 3010
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          env:
            - name: SPLIT_PROXY_APIKEY
              valueFrom:
                {{- if .Values.config.useSealed }}
                secretKeyRef:
                  name: {{ .Values.config.sealed.secretName }}
                  key: {{ .Values.config.sealed.apiKeyKey }}
                {{- else }}
                configMapKeyRef:
                  name: proxy-configmap
                  key: apiKey
                {{- end }}
            - name: SPLIT_PROXY_CLIENT_APIKEYS
              valueFrom:
                {{- if .Values.config.useSealed }}
                secretKeyRef:
                  name: {{ .Values.config.sealed.secretName }}
                  key: {{ .Values.config.sealed.clientApiKeysKey }}
                {{- else }}
                configMapKeyRef:
                  name: proxy-configmap
                  key: clientApiKeys
                {{- end }}
