apiVersion: v1
kind: Service
metadata:
  labels:
    app: proxy-sdk-svc
  name: proxy-sdk-svc
spec:
  ports:
    - name: proxy
      port: {{ .Values.service.ports.proxy }}
      protocol: TCP
      targetPort: {{ .Values.service.ports.proxy }}
    - name: admin
      port: {{ .Values.service.ports.admin }}
      protocol: TCP
      targetPort: {{ .Values.service.ports.admin }}
  selector:
    app: proxy-sdk-deployment
