{{- if not .Values.config.useSealed }}
{{- if not .Values.config.apiKey }}
{{- fail "config.apiKey is required when not using sealed secrets. Please provide it using --set config.apiKey=<your-api-key>" }}
{{- end }}
{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: eval-configmap
data:
{{- if not .Values.config.useSealed }}
  apiKey: {{ .Values.config.apiKey | quote }}
{{- end }}
