{{/* This file exists only to document the expected structure of the sealed secret */}}
{{/* The actual secret should be created separately before installing the chart */}}
{{- if .Values.useSealed }}
{{- if .Values.createSealedSecretTemplate }}
{{/* This is only for documentation/template purposes and won't be applied */}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.sealed.secretName }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  template:
    metadata:
      name: {{ .Values.sealed.secretName }}
    type: Opaque
  encryptedData:
    # These are placeholder values and must be replaced with actual sealed data
    {{ .Values.sealed.apiKeyKey }}: "encrypted-api-key-data"
{{- end }}
{{- end }}
